
-- DROP TABLE IF EXISTS job;
CREATE TABLE IF NOT EXISTS job(
    id SERIAL PRIMARY KEY,
    title VARCHAR(255),
    company VARCHAR(255),
location VARCHAR(255),
url VARCHAR(255),
description VARCHAR(255)
)